# Generated by Django 3.0.5 on 2020-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restuarent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cuisines', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('booking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('delivery', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('colour', models.CharField(choices=[('Dark Green', 'Dark Green'), ('Green', 'Green'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('White', 'White')], max_length=20)),
                ('text', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Not rated', 'Not rated')], max_length=20)),
                ('votes', models.CharField(max_length=10)),
            ],
        ),
    ]
